### ISSUE TITLE
AVS client is not using right channel ASR output, instead, is using left channel comms output

### ISSUE THREAD

**Issue by QuinnWang** [xmos/vocalfusion-stereo-avs-setup#10]
Yesterday we (Thomas Ng and I) were testing the AVS for one customer's 3channel AEC demo, we found the 3500 AVS client is using left channel (left channel of port 1E), not the right channel as mentioned in this mail thread.

So Raspberry Pi listens to the comms output, not the ASR output? Suggest to have a check, thanks

**Comment by dfollent** [comment]
Hi Quinn,
Can you please confirm that you used https://github.com/xmos/vocalfusion-stereo-avs-setup and not https://github.com/xmos/vocalfusion-avs-setup ?

**Comment by thomasngxmos** [comment]
I have checked SD Card inside the Raspi was installed with mono script. My bad for the confusion.

**Comment by DaveAtkinsonXMOS** [comment]
Could we mark this as closed? This repo is to be archived (superceded by unified vocalfusion-avs-setup repo) so I'm trying to tidy up all loose ends. Thanks!

**Comment by lucianomartin** [comment]
From the notes it looks like this issue has been fixed. @thomasngxmos and @QuinnWang, feel free to reopen it if necessary.
