### ISSUE TITLE
Documentation is outdated regarding re-authenticating Device

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/vocalfusion-stereo-avs-setup#7]
avsauth used to be the script to change the credentials to a different device. 
This is usually required to re-authenticate for a different device on the same developer account or a different developer account.

The script to do this changed in v1.5. Now avssetup has to be used instead of avsauth.

But documentation still says:
avsauth to re-authenticate your Alexa device details.

This should be changed to clarify the purpose of avsauth and avssetup

**Comment by larry-xmos** [comment]
What our modified setup.sh does is write client and product IDs into the JSON file from a plain text file `.auth_details` it had created. So yes, the idea is to run `setup.sh` (or `avssetup`) for a change of IDs.

The word _re-authenticate_ in the documentation refers to the process of obtaining a refresh token from client and product IDs

I've clarified the use of `avsauth` and `avssetup` in 26f0395, currently on open pull request #8. Do you think the description there is sufficient?

**Comment by larry-xmos** [comment]
Pull request #8 merged
