### ISSUE TITLE
Documentation about invoking auto_install.sh is inaccurate

### ISSUE THREAD

**Issue by ThomasGmeinder** [xmos/vocalfusion-stereo-avs-setup#9]
The docs say:
Run the installation script by entering ./auto_install.sh

That doesn't work though. auto_install.sh doesn't have execute permissions and needs to be sourced.
Suggesting changing to:
Run the installation script by entering ``. vocalfusion-stereo-avs-setup/auto_install.sh``

**Comment by larry-xmos** [comment]
Thanks, I've made the file executable. I will check if it can run without having to be sourced.

**Comment by larry-xmos** [comment]
Also changed in xmos/vocalfusion-avs-setup@94e1bdb

**Comment by lukeyschofield** [comment]
Hi, I've also run into this issue with permission errors. Any ideas?

**Comment by lucianomartin** [comment]
Hi @glenschofield, we are currently upgrading the scripts used in the AVS setup. Hopefully we will be able to release new versions in the coming weeks.
